is_sequence: false
sample_count: 3240
sequence_size: 1
output_dim: 2
matrix_spec {
  col_count: 259
  row_count: 1
  is_sequence_col: false
  is_sequence_row: false
  has_locality_col: true
  has_locality_row: true
  format: DENSE
}
